### PR TITLE
Update actions and pin to commit

### PR DESCRIPTION
**Pull request by marbre**
This updates the used actions to newer versions and specifies a specific
commit instead of a tag or a branch, which can be overwritten by a
maintainer of the action.

### CODE REVIEW

**Comment by dajuro** [comment]
Why do we need this?

**Comment by marbre** [comment]
> Why do we need this?

Newer actions or specific commits?

**Comment by dajuro** [comment]
> Newer actions or specific commits?
Specific commits. Are there no v3 tags?

**Comment by marbre** [comment]
> > Newer actions or specific commits?
> 
> Specific commits. Are there no v3 tags?

There are, but tags can be overwritten, commit hashes cannot.

**Review by dajuro — APPROVED** [review]

**Review by lucas-camp — APPROVED** [review]
LGTM

**Pull request merged**
