### PR TITLE
Add Renode config for STM32L4R5

### PR DESCRIPTION
**Pull request by lucas-camp**

### CODE REVIEW

**Comment by marbre** [comment]
I will review as soon as I am back to office.

**Review by heidebro — APPROVED** [review]
Looks OK to me!

But we should remember to update our Test Pipeline.

**Comment by marbre** [comment]
@lucas-camp can you please update the [README.md](https://github.com/iml130/iree-bare-metal-arm/blob/main/third_party/renode/README.md) as part of your PR?

**Review by marbre — CHANGES_REQUESTED** [review]
@lucas-camp can you please update the [README.md](https://github.com/iml130/iree-bare-metal-arm/blob/main/third_party/renode/README.md) as part of your PR?

**Comment by heidebro** [comment]
Should the main README of the Repo also be updated  in this PR aswell to mention the new target?

**Review by marbre — APPROVED** [review]

**Pull request merged**
